apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: node
          image: node:alpine
          ports:
            - containerPort: 8080
          command: ["node", "app.js"]
---
kind: Service
apiVersion: v1
metadata:
  name: myapp-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - name: myapp
      protocol: TCP
      port: 80
      targetPort: 8080
