apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: critical-app
  name: critical-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: critical-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: critical-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "critical"
        effect: "NoSchedule"
status: {}