apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-app
  namespace: default  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: critical-app
  template:
    metadata:
      labels:
        app: critical-app
    spec:
      containers:
      - name: app-container
        image: my-app-image:latest
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "critical"
        effect: "NoSchedule"
