apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app 
  labels:
    app: backend-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app 
  template:
    metadata:
      labels:
        app: backend-app 
    spec:
      containers:
      - name: backend-app 
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      nodeSelector:
        role: backend
