apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-app
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - image: nginx
          name: nginx
      nodeSelector:
        role: backend
