apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: default  # Adjust the namespace if different
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app-container
        image: nginx:latest
      nodeSelector:
        role: backend