apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: view-pods-services
rules:
- apiGroups: [""]  
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"] 


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-view-pods-services
  namespace: dev
subjects:
- kind: User
  name: dev-user 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-pods-services  
  apiGroup: rbac.authorization.k8s.io
