apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: role-bind
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-pods-services
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: dev-user
