apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: billing-app
  name: billing-app
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: billing-app
        role: billing
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}