apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: billing-app-network-policy
  namespace: finance
spec:
  podSelector:
    matchLabels:
      app: billing-app
  policyTypes:
   - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: web
controlplane $
