apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: kube-system  # Deploying in kube-system is common for system-level agents
spec:
  selector:
    matchLabels:
      app: log-agent
  template:
    metadata:
      labels:
        app: log-agent
    spec:
      containers:
        - name: log-agent
          image: fluent/fluentd:v1.12-1 # Replace with your preferred logging agent image
          env:
            - name: FLUENTD_CONF
              value: "fluent.conf" # Assuming you have a configuration file named fluent.conf
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        env: production  # Ensure the DaemonSet runs only on nodes labeled with env=production
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers