apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-01
  name: app-01
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-01
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: app-01
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000