apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app01
  name: app01-svc
  namespace: prod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: app01
  type: NodePort
status:
  loadBalancer: {}