# kubectl create ns prod
# vim q5-nginx-dep.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app01
  template:
    metadata:
      labels:
        app: app01
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app01-svc
  namespace: prod
spec:
  selector:
    app: app01
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001

# kubectl apply -f q5-nginx-dep.yaml
# kubectl get deployment app01 -n prod
# kubectl get pods -n prod
# kubectl get svc -n prod
# kubectl get nodes -o wide
# curl http://<node-ip>:30001
