apiVersion: v1
kind: Pod
metadata:
  name: database-app
spec:
  containers:
  - name: database-container
    image: nginx  # Replace with the actual database container image
    volumeMounts:
    - mountPath: /usr/share/nginx/html  # Example mount path (adjust for your app)
      name: database-storage
  volumes:
  - name: database-storage
    persistentVolumeClaim:
      claimName: database-pvc