apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: rancher.io/local-path # indicates that this StorageClass does not support automatic provisioning
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain