apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database-app
  name: database-app
spec:
  containers:
  - image: nginx
    name: database-app
    volumeMounts:
      - name: data
        mountPath: /usr/share/nginx/html
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pv

---

kind: PersistentVolume
metadata:
  name: pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: sc
  hostPath:
    path: /app


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: sc


---


apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc
provisioner: rancher.io/local-path # indicates that this StorageClass does not support automatic provisio>
volumeBindingMode: WaitForFirstConsumer