apiVersion: v1
kind: PersistentVolume
metadata:
  name: fast-storage-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-storage
  hostPath:
    path: /mnt/data/fast-storage


    //pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-storage 

  //pod

apiVersion: v1
kind: Pod
metadata:
  name: database-app
spec:
  containers:
  - name: database
    image: nginx:latest 
    volumeMounts:
    - mountPath: /data
      name: fast-storage-volume
  volumes:
  - name: fast-storage-volume
    persistentVolumeClaim:
      claimName: fast-storage-pvc