apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/database"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-storage

---


apiVersion: v1
kind: Pod
metadata:
  name: database-app
spec:
  containers:
  - name: database-container
    image: mysql:latest
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: "/var/lib/mysql"
      name: database-storage
  volumes:
  - name: database-storage
    persistentVolumeClaim:
      claimName: database-pvc