apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-storage
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fast-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: fast-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/database-pv
---
apiVersion: v1
kind: Pod
metadata:
  name: database-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: database-storage
          mountPath: /var/lib/database
  volumes:
    - name: database-storage
      persistentVolumeClaim:
        claimName: database-pvc
