apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database-app
  name: database-app
spec:
  containers:
  - image: nginx
    name: database-app
    resources: {}
    volumeMounts:
    - mountPath: "/var/www/html"
      name: my-pv
  volumes:
  - name: my-pv
    persistentVolumeClaim:
      claimName: my-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}