apiVersion: v1
kind: Pod
metadata:
  name: database-app
spec:
  containers:
  - name: database-container
    image: mysql:latest
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: database-storage
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "kucing"  
  volumes:
  - name: database-storage
    persistentVolumeClaim:
      claimName: pvc-database
