apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-q7
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: fast-storage
  hostPath:
    path: "/mnt/data/"