apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing
  labels:
    app: data-processing
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: data-processing
              topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: web-server
              topologyKey: "kubernetes.io/hostname" 
      containers:
        - name: data-processor
          image: nginx:latest
          ports:
            - containerPort: 8080